import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

export async function GET() {
  try {
    const cars = [
      {
        make: "Mercedes-Benz",
        model: "S-Klasa",
        generation: "W223",
        year: 2024,
        mileage: 150,
        engineCapacity: 2999,
        power: 381,
        fuelType: "PETROL",
        transmission: "AUTOMATIC",
        driveTrain: "AWD",
        vin: "WDD2231761X998811",
        price: 750000,
        currency: "PLN",
        vatReclaimable: true,
        vatType: "VAT_23",
        description: "Zupełnie nowa klasa S w wersji Long. Pełen pakiet systemów asystujących, skrętna tylna oś, cyfrowe reflektory DIGITAL LIGHT.",
        images: [],
        features: ["Skrętna tylna oś", "DIGITAL LIGHT", "Masaże w fotelach", "Wyświetlacz HUD AR"],
        status: "AVAILABLE",
        slug: "mercedes-benz-s-klasa-w223-2024",
        accidentFree: true,
        bodyType: "SEDAN",
        color: "Czarny",
        doors: 4,
        firstRegistration: new Date("2024-02-10"),
        originCountry: "Polska",
        powerUnit: "KM",
        seats: 5,
        serviceHistory: true,
        upholstery: "Skóra Nappa",
        condition: "NEW",
        firstOwner: true,
        registeredInPoland: true,
        registrationNumber: "W0 KLASAS"
      },
      {
        make: "Porsche",
        model: "Panamera",
        generation: "G3",
        year: 2024,
        mileage: 3500,
        engineCapacity: 2894,
        power: 353,
        fuelType: "PETROL",
        transmission: "AUTOMATIC",
        driveTrain: "AWD",
        vin: "WP0ZZZ97ZNS123999",
        price: 680000,
        currency: "PLN",
        vatReclaimable: true,
        vatType: "VAT_23",
        description: "Nowa generacja Porsche Panamera. Sportowy charakter limuzyny, pneumatyczne zawieszenie PASM, sportowy układ wydechowy.",
        images: [],
        features: ["Zawieszenie pneumatyczne PASM", "Sportowy wydech", "Nagłośnienie BOSE", "Pakiet Sport Chrono"],
        status: "AVAILABLE",
        slug: "porsche-panamera-g3-2024",
        accidentFree: true,
        bodyType: "SEDAN",
        color: "Szary Wulkan",
        doors: 4,
        firstRegistration: new Date("2024-01-20"),
        originCountry: "Polska",
        powerUnit: "KM",
        seats: 4,
        serviceHistory: true,
        upholstery: "Skóra Czarna",
        condition: "USED",
        firstOwner: true,
        registeredInPoland: true,
        registrationNumber: "PO PANAM"
      },
      {
        make: "BMW",
        model: "Seria 7",
        generation: "G70",
        year: 2023,
        mileage: 12000,
        engineCapacity: 2998,
        power: 381,
        fuelType: "PETROL",
        transmission: "AUTOMATIC",
        driveTrain: "AWD",
        vin: "WBA7ER00000G70123",
        price: 620000,
        currency: "PLN",
        vatReclaimable: true,
        vatType: "VAT_23",
        description: "Niesamowite BMW Serii 7 z ekranem kinowym z tyłu (Theater Screen). Auto z polskiego salonu, na gwarancji producenta.",
        images: [],
        features: ["BMW Theater Screen", "Kryształowe reflektory Iconic Glow", "Drzwi otwierane automatycznie", "System Bowers & Wilkins"],
        status: "AVAILABLE",
        slug: "bmw-seria-7-g70-2023",
        accidentFree: true,
        bodyType: "SEDAN",
        color: "Czarny Szafir",
        doors: 4,
        firstRegistration: new Date("2023-08-15"),
        originCountry: "Polska",
        powerUnit: "KM",
        seats: 5,
        serviceHistory: true,
        upholstery: "Skóra Merino",
        condition: "USED",
        firstOwner: true,
        registeredInPoland: true,
        registrationNumber: "DW 7ER"
      },
      {
        make: "Audi",
        model: "A8",
        generation: "D5",
        year: 2022,
        mileage: 45000,
        engineCapacity: 2995,
        power: 340,
        fuelType: "PETROL",
        transmission: "AUTOMATIC",
        driveTrain: "AWD",
        vin: "WAUZZZF88MN987111",
        price: 450000,
        currency: "PLN",
        vatReclaimable: false,
        vatType: "VAT_MARGIN",
        description: "Luksusowa limuzyna Audi A8 Long. Maksymalne wyposażenie dla pasażerów z tyłu, ekrany, wentylacja i masaże.",
        images: [],
        features: ["Reflektory Matrix LED", "Pakiet Rear Seat Entertainment", "Skrętna oś", "Dociąganie drzwi"],
        status: "AVAILABLE",
        slug: "audi-a8-d5-2022-long",
        accidentFree: true,
        bodyType: "SEDAN",
        color: "Granatowy",
        doors: 4,
        firstRegistration: new Date("2022-05-10"),
        originCountry: "Niemcy",
        powerUnit: "KM",
        seats: 4,
        serviceHistory: true,
        upholstery: "Skóra Valcona",
        condition: "USED",
        firstOwner: false,
        registeredInPoland: true,
        registrationNumber: "KR A8L"
      }
    ];

    for (const car of cars) {
      await prisma.vehicle.create({
        data: car as any
      });
    }

    return NextResponse.json({ success: true, message: "Dodano 4 auta do bazy (całkowicie bez linków i zdjęć)!" });
  } catch (error) {
    console.error("Błąd podczas dodawania:", error);
    return NextResponse.json({ success: false, error: "Sprawdź terminal, wystąpił błąd." }, { status: 500 });
  }
}