import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

export async function GET() {
  try {
    const cars = [
      {
        make: "Audi",
        model: "RS Q8",
        generation: "4M",
        year: 2023,
        mileage: 24500,
        engineCapacity: 3996,
        power: 600,
        fuelType: "PETROL",
        transmission: "AUTOMATIC",
        driveTrain: "AWD",
        vin: "WAUZZZ4M1PD001122",
        price: 720000,
        currency: "PLN",
        vatReclaimable: true,
        vatType: "VAT_23",
        description: "Potężne Audi RS Q8 z silnikiem 4.0 V8 o mocy 600 KM. Auto z polskiego salonu, na przedłużonej gwarancji. Założona folia ochronna PPF na froncie.",
        images: [],
        features: ["Hamulce ceramiczne RS", "Sportowy układ wydechowy RS", "Nagłośnienie Bang & Olufsen 3D", "Reflektory HD Matrix LED"],
        status: "AVAILABLE",
        slug: "audi-rsq8-4m-2023",
        accidentFree: true,
        bodyType: "SUV",
        color: "Czarny Mythos",
        doors: 5,
        firstRegistration: new Date("2023-05-12"),
        originCountry: "Polska",
        powerUnit: "KM",
        seats: 5,
        serviceHistory: true,
        upholstery: "Skóra Valcona RS",
        condition: "USED",
        firstOwner: true,
        registeredInPoland: true,
        registrationNumber: "W1 RSQ8"
      },
      {
        make: "Mercedes-Benz",
        model: "GLE",
        generation: "W167",
        year: 2022,
        mileage: 58000,
        engineCapacity: 2925,
        power: 330,
        fuelType: "DIESEL",
        transmission: "AUTOMATIC",
        driveTrain: "AWD",
        vin: "WDC1671231A112233",
        price: 415000,
        currency: "PLN",
        vatReclaimable: true,
        vatType: "VAT_23",
        description: "Mercedes-Benz GLE 400 d 4MATIC. Idealny, mocny i oszczędny silnik diesla. Samochód w pełnym pakiecie wizualnym AMG zewnętrznym i wewnętrznym.",
        images: [],
        features: ["Pakiet sportowy AMG", "Zawieszenie pneumatyczne AIRMATIC", "Nagłośnienie Burmester", "Reflektory MULTIBEAM LED"],
        status: "AVAILABLE",
        slug: "mercedes-gle-400d-w167-2022",
        accidentFree: true,
        bodyType: "SUV",
        color: "Biały Diamentowy Bright",
        doors: 5,
        firstRegistration: new Date("2022-09-20"),
        originCountry: "Polska",
        powerUnit: "KM",
        seats: 5,
        serviceHistory: true,
        upholstery: "Skóra Artico/Dinamica Czarna",
        condition: "USED",
        firstOwner: true,
        registeredInPoland: true,
        registrationNumber: "PO 400D"
      },
      {
        make: "Land Rover",
        model: "Discovery",
        generation: "V",
        year: 2023,
        mileage: 18500,
        engineCapacity: 2997,
        power: 250,
        fuelType: "DIESEL",
        transmission: "AUTOMATIC",
        driveTrain: "AWD",
        vin: "SALRA2AG1PH003344",
        price: 345000,
        currency: "PLN",
        vatReclaimable: true,
        vatType: "VAT_23",
        description: "Land Rover Discovery V D250. Wybitnie uniwersalny i komfortowy SUV. Wersja 7-osobowa, bezwypadkowy, serwisowany wyłącznie w ASO.",
        images: [],
        features: ["Wersja 7-miejscowa", "System Terrain Response 2", "Zawieszenie pneumatyczne", "System nagłośnienia Meridian"],
        status: "AVAILABLE",
        slug: "land-rover-discovery-v-2023",
        accidentFree: true,
        bodyType: "SUV",
        color: "Eiger Grey",
        doors: 5,
        firstRegistration: new Date("2023-03-05"),
        originCountry: "Polska",
        powerUnit: "KM",
        seats: 7,
        serviceHistory: true,
        upholstery: "Skóra Windsor Ebony",
        condition: "USED",
        firstOwner: true,
        registeredInPoland: true,
        registrationNumber: "KR LRD5"
      },
      {
        make: "BMW",
        model: "X6",
        generation: "G06",
        year: 2023,
        mileage: 31000,
        engineCapacity: 2998,
        power: 340,
        fuelType: "PETROL",
        transmission: "AUTOMATIC",
        driveTrain: "AWD",
        vin: "WBAKU610609M55667",
        price: 460000,
        currency: "PLN",
        vatReclaimable: true,
        vatType: "VAT_23",
        description: "BMW X6 xDrive40i M Sport. Agresywna sylwetka coupe, świetne osiągi dzięki silnikowi benzynowemu 3.0. Stan idealny, auto z polskiego salonu.",
        images: [],
        features: ["Pakiet sportowy M", "Podświetlany grill Iconic Glow", "Reflektory laserowe BMW", "System domykania drzwi"],
        status: "AVAILABLE",
        slug: "bmw-x6-g06-40i-2023",
        accidentFree: true,
        bodyType: "SUV",
        color: "Czarny Szafir",
        doors: 5,
        firstRegistration: new Date("2023-11-15"),
        originCountry: "Polska",
        powerUnit: "KM",
        seats: 5,
        serviceHistory: true,
        upholstery: "Skóra Vernasca",
        condition: "USED",
        firstOwner: true,
        registeredInPoland: true,
        registrationNumber: "DW X6M"
      }
    ];

    for (const car of cars) {
      await prisma.vehicle.create({
        data: car as any
      });
    }

    return NextResponse.json({ success: true, message: "Dodano 4 nowe auta SUV do bazy (całkowicie bez zdjęć)!" });
  } catch (error) {
    console.error("Błąd podczas dodawania:", error);
    return NextResponse.json({ success: false, error: "Sprawdź terminal, wystąpił błąd." }, { status: 500 });
  }
}