import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

export async function GET() {
  try {
    const car = {
      make: "BMW",
      model: "M5",
      generation: "F90",
      year: 2018,
      mileage: 61000,
      engineCapacity: 4395,
      power: 600,
      fuelType: "PETROL",
      transmission: "AUTOMATIC",
      driveTrain: "AWD",
      vin: "WBSJF010X0G000000",
      price: 279000,
      currency: "PLN",
      vatReclaimable: true,
      vatType: "VAT_23",
      description: "Niezwykle bogato skonfigurowane BMW M5 F90 z polskiego salonu. Egzemplarz całkowicie bezwypadkowy, wyróżniający się matowym lakierem z palety BMW Individual: Frozen dark red metallic. Pod maską potężne 4.4 V8 o mocy 600 KM. Lista wyposażenia jest ogromna i obejmuje m.in. hamulce węglowo-ceramiczne, nagłośnienie Bowers & Wilkins High End Sound System, sportowy układ wydechowy M, wentylowane fotele, miękkie domykanie drzwi oraz pakiet M Driver's uwalniający pełen potencjał auta na torze.",
      images: [],
      imagePublicIds: [],
      primaryImageIndex: 0,
      youtubeUrl: "",
      features: [
        "ABS",
        "BAS/AFU - system wspomagania nagłego hamowania",
        "EDS",
        "Lane Assist - kontrola zmiany pasa ruchu",
        "aktywne rozpoznawanie znaków ograniczenia prędkości",
        "aktywny asystent hamowania awaryjnego",
        "asystent hamowania - Brake Assist",
        "asystent pasa ruchu",
        "asystent świateł drogowych",
        "automat. hamulec postojowy",
        "automatyczne światła",
        "blokada drzwi podczas jazdy",
        "czujnik deszczu",
        "czujnik martwego pola",
        "czujnik zmierzchu",
        "czujniki parkowania - przód",
        "czujniki parkowania - tył",
        "dynamiczne światła doświetlające zakręty",
        "elektroniczny system rozdziału siły hamowania",
        "kamera cofania",
        "kontrola trakcji (ASR)",
        "ogranicznik prędkości",
        "poduszka pow. chroniąca kolana kierowcy",
        "poduszka pow. chroniąca kolana pasażera",
        "poduszka pow. kierowcy",
        "poduszka pow. pasażera",
        "poduszki pow. boczne - przód",
        "poduszki pow. kurtynowe - przód",
        "poduszki pow. kurtynowe - tył",
        "stabilizacja toru jazdy (ESP)",
        "system hamowania awaryjnego dla ochrony pieszych",
        "system ostrzegania przed kolizją",
        "system powiadamiania o wypadku",
        "system rozpoznawania znaków drogowych",
        "uchwyt ISOFIX",
        "wspomaganie ruszania na wzniesieniu",
        "światła do jazdy dziennej",
        "HUD (wyświetlacz przezierny)",
        "asystent parkowania",
        "autonomiczny system parkowania",
        "dach: z tworzywa sztucznego",
        "domykanie szyb przy zamykaniu auta",
        "dzielona tylna kanapa",
        "elektrochromatyczne lusterka boczne",
        "elektrochromatyczne lusterko wsteczne",
        "elektryczne lusterka",
        "elektryczne szyby przednie",
        "elektryczne szyby tylne",
        "elektrycznie sterowana klapa bagażnika",
        "elektrycznie ustawiany fotel kierowcy",
        "elektrycznie ustawiany fotel pasażera",
        "fotele przednie wentylowane",
        "fotele sportowe",
        "kierownica sportowa",
        "kierownica wielofunkcyjna",
        "kierownica ze sterowaniem radia",
        "klimatyzacja: automatyczna 4-strefowa",
        "kolumna kierownicy regulowana elektrycznie",
        "lusterka boczne składane elektrycznie",
        "podgrzewana kierownica",
        "podgrzewana tylna szyba",
        "podgrzewane tylne siedzenia",
        "podgrzewany fotel kierowcy",
        "podgrzewany fotel pasażera",
        "podłokietniki - przód",
        "podłokietniki - tył",
        "radio fabryczne z CD i MP3",
        "regul. elektr. podparcia lędźwiowego - kierowca",
        "regul. elektr. podparcia lędźwiowego - pasażer",
        "regulacja wysokości fotela",
        "regulowana kierownica",
        "regulowane zawieszenie",
        "regulowany dyferencjał centralny",
        "skórzana kierownica",
        "smartcard / hands free / smartkey",
        "system głośnomówiący",
        "system start-stop",
        "tempomat",
        "zawieszenie sportowe",
        "łopatki zmiany biegów",
        "Android Auto",
        "Apple CarPlay",
        "autoalarm",
        "bluetooth",
        "centralny zamek",
        "czujniki ciśnienia w oponach",
        "dostęp do internetu",
        "dźwignia zmiany biegów wykończona skórą",
        "ekran dotykowy",
        "elektroniczna regul. charakterystyki zawieszenia",
        "elektroniczne zegary (wirtualny kokpit)",
        "elektroniczny wtrysk",
        "gniazdo USB",
        "hamulce z kompozytów ceramicznych",
        "kamera panoramiczna 360",
        "kamera w lusterku bocznym",
        "komputer pokładowy",
        "lampy do jazdy dziennej diodowe LED",
        "lampy tylne w technologii LED",
        "nawigacja satelitarna",
        "oświetlenie wnętrza (ambient lighting)",
        "przyciemniane tylne szyby",
        "reflektory adaptacyjne",
        "siedzenie z pamięcią ustawienia",
        "spoiler",
        "system nagłośnienia",
        "tłumik sportowy",
        "zestaw głośnomówiący",
        "zmieniarka CD",
        "ładowanie bezprzewodowe urządzeń",
        "keyless Go",
        "keyless entry",
        "uruchamianie silnika bez użycia kluczyków",
        "felgi: aluminiowe 20",
        "opony: letnie"
      ],
      status: "AVAILABLE",
      slug: "bmw-m5-f90-frozen-red-2018",
      accidentFree: true,
      bodyType: "SEDAN",
      color: "Frozen dark red metallic (BMW Individual)",
      doors: 4,
      firstRegistration: new Date("2018-04-13"),
      originCountry: "Polska",
      powerUnit: "KM",
      seats: 5,
      serviceHistory: true,
      upholstery: "Skóra Individual",
      condition: "USED",
      firstOwner: false,
      registeredInPoland: true,
      registrationNumber: "RZ5550T"
    };

    await prisma.vehicle.create({
      data: car as any
    });

    return NextResponse.json({ 
      success: true, 
      message: "Pomyślnie dodano do bazy BMW M5 F90 z pełną listą wyposażenia!" 
    });
  } catch (error) {
    console.error("Błąd podczas dodawania:", error);
    return NextResponse.json({ 
      success: false, 
      error: "Wystąpił błąd podczas dodawania auta. Sprawdź terminal." 
    }, { status: 500 });
  }
}